//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MageLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MageLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error launching the game..
        /// </summary>
        public static string MessageBox_Message_Error_Launching {
            get {
                return ResourceManager.GetString("MessageBox_Message_Error_Launching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to cancel patching and exit?.
        /// </summary>
        public static string MessageBox_Message_Exit_Confirm {
            get {
                return ResourceManager.GetString("MessageBox_Message_Exit_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magestorm is already running..
        /// </summary>
        public static string MessageBox_Message_Game_Already_Running {
            get {
                return ResourceManager.GetString("MessageBox_Message_Game_Already_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error during the patching process..
        /// </summary>
        public static string MessageBox_Message_Patch_Error {
            get {
                return ResourceManager.GetString("MessageBox_Message_Patch_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must run the launcher as Administrator..
        /// </summary>
        public static string MessageBox_Message_RunAsAdministrator {
            get {
                return ResourceManager.GetString("MessageBox_Message_RunAsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBox_Title_Error {
            get {
                return ResourceManager.GetString("MessageBox_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magestorm Launcher.
        /// </summary>
        public static string MessageBox_Title_Launcher {
            get {
                return ResourceManager.GetString("MessageBox_Title_Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch Error.
        /// </summary>
        public static string MessageBox_Title_Patch_Error {
            get {
                return ResourceManager.GetString("MessageBox_Title_Patch_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream MouseOver {
            get {
                return ResourceManager.GetStream("MouseOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://patch.magestorm.net/magestorm.zip.
        /// </summary>
        public static string URL_Patch {
            get {
                return ResourceManager.GetString("URL_Patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://patch.magestorm.net/version.txt.
        /// </summary>
        public static string URL_Version {
            get {
                return ResourceManager.GetString("URL_Version", resourceCulture);
            }
        }
    }
}
