//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MageServer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_Disconnect {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_Disconnect() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MageServer.Resources.Strings_Disconnect", typeof(Strings_Disconnect).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Error.
        /// </summary>
        internal static string AuthenticationError {
            get {
                return ResourceManager.GetString("AuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You attempted to use a cheat program..
        /// </summary>
        internal static string CheatProgram {
            get {
                return ResourceManager.GetString("CheatProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading your character..
        /// </summary>
        internal static string ErrorLoadingCharacter {
            get {
                return ResourceManager.GetString("ErrorLoadingCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Version.
        /// </summary>
        internal static string InvalidVersion {
            get {
                return ResourceManager.GetString("InvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You attempted to use a spell list hack..
        /// </summary>
        internal static string ListHack {
            get {
                return ResourceManager.GetString("ListHack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logoff.
        /// </summary>
        internal static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Connection.
        /// </summary>
        internal static string LostConnection {
            get {
                return ResourceManager.GetString("LostConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another user logged into this account..
        /// </summary>
        internal static string MultipleLogin {
            get {
                return ResourceManager.GetString("MultipleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You attempted to use a spell pick hack..
        /// </summary>
        internal static string PickHack {
            get {
                return ResourceManager.GetString("PickHack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ping is too high..
        /// </summary>
        internal static string PingSpiking {
            get {
                return ResourceManager.GetString("PingSpiking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is being restarted..
        /// </summary>
        internal static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were speedhacking..
        /// </summary>
        internal static string SpeedHack {
            get {
                return ResourceManager.GetString("SpeedHack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You casted a spell you do not have..
        /// </summary>
        internal static string SpellHack {
            get {
                return ResourceManager.GetString("SpellHack", resourceCulture);
            }
        }
    }
}
